name: Build OllamaBridge

on:
  push:
    branches:
      - '*'
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    name: Build OllamaBridge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          # 排除一些不常用的组合
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # 设置输出文件名称
          OUTPUT="OllamaBridge"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            OUTPUT="${OUTPUT}.exe"
          fi
          
          # 添加OS和架构到文件名
          FILENAME="${OUTPUT}-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            FILENAME="${FILENAME}.exe"
          fi
          
          # 编译
          echo "Building for ${{ matrix.goos }}-${{ matrix.goarch }}..."
          go build -v -o "${FILENAME}" -ldflags="-s -w -X main.Version=$(git describe --tags --always --dirty)" ./OllamaBridge.go
          
          # 为Linux和macOS添加执行权限
          if [ "${{ matrix.goos }}" != "windows" ]; then
            chmod +x "${FILENAME}"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OllamaBridge-${{ matrix.goos }}-${{ matrix.goarch }}
          path: OllamaBridge-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
          retention-days: 5

  # 当有新的tag推送时，创建GitHub Release
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: OllamaBridge-*/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
